### ISSUE TITLE
Can not render markdown description properly

### ISSUE THREAD

**Issue by drunkwcodes** [di/markdown-description-example#1]
I followed the [guide](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi) and upgraded setuptools and twine, but it didn't render markdown properly after uploading.

And `python setup.py check` says 
```
python\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: '
long_description_content_type'
```
Here is my project: https://pypi.org/project/qquiz/

I used twine version 1.11.0 (pkginfo: 1.4.2, requests: 2.18.4, setuptools: 39.0.1, requests-toolbelt: 0.8.0, tqdm: 4.19.8) on Windows.

**Comment by di** [comment]
@drunkwcodes Thanks for the report! Sorry this isn't working for you.

Looks like you're building wheels as well as source distributions, and therefore hitting https://github.com/pypa/wheel/issues/231 (which has an open PR, https://github.com/pypa/wheel/pull/232)

In short: `wheel` is not writing out the correct `Metadata-Version`, `twine` prefers sending wheels to PyPI before source distributions, and PyPI only pulls metadata from the first distribution sent for a new release.

You can wait until that fix to `wheel` is accepted and merged, or you could fix this by sending the distributions one at a time, with the source distribution first, in your next release. E.g.:

```
$ python setup.py sdist bdist_wheel
$ twine upload dist/qquiz-0.1.0b4.tar.gz 
$ twine upload qquiz-0.1.0b4-py3-none-any.whl 
```

**Comment by drunkwcodes** [comment]
Thanks for your quick reply, the workaround works well. I should read the whole page before trying!

:ok_hand:  :ok_hand:

**Comment by defjaf** [comment]
Thanks! For what it's worth, I note that the markdown rendering isn't perfect: see, e.g., [this code block](https://pypi.org/project/pip-upgrade-outdated/1.0b3/).

Is there a better place to report this (assuming this isn't a problem on my side)?

**Comment by di** [comment]
@defjaf Please raise an issue over at https://github.com/pypa/warehouse/issues, it's been mentioned before but I don't think there's an issue for it, and it seems like it is a trivial styling change we can make (definitely not a problem on your side).

We're also working on adding Github Flavored Markdown (GFM) support at the moment, which might help with a lot of the other CommonMark shortcomings, see https://github.com/pypa/packaging-problems/issues/126.

**Comment by defjaf** [comment]
Added this to the [ongoing discussion of PIP566 compliance](https://github.com/pypa/warehouse/issues/3299).

**Comment by di** [comment]
It's not really related to PEP 566 compliance since it's just styling. I created https://github.com/pypa/warehouse/issues/3330.

**Comment by defjaf** [comment]
@di that makes sense: sorry for the extra work!

**Comment by gbtami** [comment]
I still has this problem with https://github.com/gbtami/Fairy-Stockfish
See https://pypi.org/project/pyffish/
I'm on Ubuntu 18.04 
>>> import setuptools
>>> setuptools.__version__
'40.8.0'
>>> import twine
>>> twine.__version__
'1.13.0'
