### ISSUE TITLE
What did I miss !

### ISSUE THREAD

**Issue by Natim** [di/markdown-description-example#5]
I am trying to configure a pypi project markdown longdescription here: https://pypi.org/project/aioexponent/

I though I configured correctly my setup.py https://github.com/Chefclub/expo-server-sdk-asyncio/blob/0.5.0/setup.py#L19

But the description still doesn't show properly.

**Comment by hugovk** [comment]
Make sure you're using recent tools:

```
pip install --upgrade setuptools twine wheel
```

See https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/ for more info.

**Comment by Natim** [comment]
Fixed it thanks.

**Comment by Natim** [comment]
Actually it did not: https://pypi.org/project/aioexponent/

**Comment by Natim** [comment]
I missed the wheel one. Thanks
